const { _electron: electron } = require('playwright');
const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
const { spawn, execFileSync } = require('child_process');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'verification');
const { version } = require('../package.json');
const data = fs.mkdtempSync(path.join(require('os').tmpdir(), 'session-launcher-release-'));
const exe = path.join(root, 'release', version, 'win-unpacked/iRacing Session Launcher.exe');
const env = { ...process.env, LAUNCHER_DATA_DIR: data };
delete env.ELECTRON_RUN_AS_NODE;
fs.mkdirSync(output, { recursive: true });
let app;
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
(async () => {
  app = await electron.launch({ executablePath: exe, env });
  const page = await app.firstWindow();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.waitForFunction(async () => (await window.launcher.getState()).monitor.checkedAt !== null);
  await wait(1500);
  const state = await page.evaluate(() => window.launcher.getState());
  assert.equal(state.version, version);
  assert.notEqual(state.monitor.phase, 'error');
  assert.equal(state.config.apps.length, 0);
  assert.equal(state.config.monitorEnabled, true);
  assert.equal(state.config.stopWhenIracingCloses, true);
  assert.equal(state.configPath, path.join(data, 'apps.json'));
  assert.equal(await page.locator('.empty').first().isVisible(), true);
  await page.screenshot({ path: path.join(output, 'release-preview.png') });
  await page.locator('#hideToTray').click();
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isVisible()), false);
  const second = spawn(exe, [], { env, stdio: 'ignore' });
  await new Promise((resolve, reject) => { second.once('exit', resolve); second.once('error', reject); });
  await wait(300);
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().length), 1);
  assert.equal(await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isVisible()), true);
  const parentPid = await app.evaluate(() => process.pid);
  await app.close();
  app = null;
  await wait(1600);
  const probe = path.join(root, 'release', version, 'win-unpacked/resources/build-assets/SessionProbe.exe');
  const snapshot = JSON.parse(execFileSync(probe, ['--once'], { windowsHide: true, encoding: 'utf8' }));
  assert.equal(snapshot.processes.some((process) => process.name === 'SessionProbe.exe' && process.parentPid === parentPid), false);
  assert.deepEqual(errors, []);
  const artifactSha256 = require('crypto').createHash('sha256').update(fs.readFileSync(path.join(path.dirname(exe), 'resources/app.asar'))).digest('hex');
  const result = { passed: true, version: state.version, artifactSha256, cleanProfile: true, trayRestore: true, singleInstance: true, cleanExit: true, rendererErrors: errors };
  fs.writeFileSync(path.join(output, 'release-result.json'), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result));
})().catch((error) => { console.error(error); process.exitCode = 1; }).finally(async () => {
  if (app) await app.close();
  if (path.dirname(data) !== path.resolve(require('os').tmpdir()) || !path.basename(data).startsWith('session-launcher-release-')) throw new Error('Unexpected test directory.');
  fs.rmSync(data, { recursive: true, force: true, maxRetries: 3, retryDelay: 500 });
});
